version: "3"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'derp'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dbvol:/var/lib/mysql
volumes:
  dbvol: